spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/Opt/hsqldb/grapql_demo
  jpa:
    hibernate:
      ddl-auto: update

graphql:
  tools:
    schemaLocationPattern: "**/*.graphqls"
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
